# Copyright (c) 2016-present Sven Greb <development@svengreb.de>
# This source code is licensed under the MIT license found in the license file.

#+----------------+
#+ Plugin Support +
#+----------------+
#+--- tmux-prefix-highlight ---+
set -g @prefix_highlight_output_prefix "#[fg=brightcyan]#[bg=black]#[nobold]#[noitalics]#[nounderscore]#[bg=brightcyan]#[fg=black]"
set -g @prefix_highlight_output_suffix ""
set -g @prefix_highlight_copy_mode_attr "fg=brightcyan,bg=black,bold"

#+--------+
#+ Status +
#+--------+
#+--- Bars ---+
status_color="#( [ $(tmux show-option -qv key-table) = 'off' ] && echo 'magenta' || echo 'blue' )"
active_color="#( [ $(tmux show-option -qv key-table) = 'off' ] && echo 'red' || echo 'cyan' )"

set -g status-left "#[fg=black,bg=$status_color,bold] #S #[fg=$status_color,bg=black,nobold,noitalics,nounderscore]"
is_keys_off_indicator="#{prefix_highlight}#[fg=red,bg=black,nobold,noitalics,nounderscore]#([ $(tmux show-option -qv key-table) = 'off' ] && echo '')#[fg=black,bg=red]#([ $(tmux show-option -qv key-table) = 'off' ] && echo ' OFF ')#[default]"
is_keys_off_seperator="#{prefix_highlight}#[fg=brightblack,bg=red,nobold,noitalics,nounderscore]#([ $(tmux show-option -qv key-table) = 'off' ] && echo '')#{prefix_highlight}#[fg=brightblack,bg=black,nobold,noitalics,nounderscore]#([ $(tmux show-option -qv key-table) = 'off' ] || echo '')"
set -g status-right "$is_keys_off_indicator$is_keys_off_seperator#[fg=white,bg=brightblack]\
#[fg=white,bg=brightblack] #H #[fg=$active_color,bg=brightblack,nobold,noitalics,nounderscore]\
#[fg=black,bg=$active_color,bold] ${NORD_TMUX_STATUS_DATE_FORMAT}  ${NORD_TMUX_STATUS_TIME_FORMAT} "
set -g status-right-length 80
set -g status-left-length 80

#+--- Windows ---+
set -g window-status-format "#[fg=black,bg=brightblack,nobold,noitalics,nounderscore] #[fg=white,bg=brightblack]#I #[fg=white,bg=brightblack,nobold,noitalics,nounderscore] #[fg=white,bg=brightblack]#W #F #[fg=brightblack,bg=black,nobold,noitalics,nounderscore]"
set -g window-status-current-format "#[fg=black,bg=$active_color,nobold,noitalics,nounderscore] #[fg=black,bg=$active_color]#I #[fg=black,bg=$active_color,nobold,noitalics,nounderscore] #[fg=black,bg=$active_color]#W #F #[fg=$active_color,bg=black,nobold,noitalics,nounderscore]"
set -g window-status-separator ""
